id: I797DD744
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T05:24:29+00:00'
last_modified: '2022-06-13T12:47:38.912672+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3438
  title: རྩ་ཤེས་ཀྱི་ཊཱི་ཀ་དང་ཚིག་གསལ་གྱི་དཀའ་གནད་དང་སྤྱི་སྡོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    474A:
      image_group_id: I3CN8574
      title: ''
      total_pages: ''
      order: 1
      base_file: 474A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
